MsgBus: allow JSON serialization/deserialization to work for instances of nested classes
Use getName() instead of getCanonicalName() to get the object's class name.

getCanonicalName() → "pkg.OuterClass.StaticNestedClass"
getName()          → "pkg.OuterClass$StaticNestedClass"

Using the canonical name results in:

  java.lang.ClassNotFoundException: pkg.OuterClass.StaticNestedClass

Change-Id: Ic8c03c62863d7d4a0a1b2b1cfe2897652035e9dc