Reverse completion order in NexusScanDataWriter
The previous ordering causes issues when running scans on I07 as the
file is reopened to complete the metadata writing but cannot due to:
HDF5FileFactory - Could not acquire access to file
hdf.hdf5lib.exceptions.HDF5FileInterfaceException: Bad file ID accessed

Change-Id: I3be562705e0b63503ed95fb8d79cbbda872a4763