I09 - Fix RegionProgressComposite errors
If the SES live perspective was ever closed, I could see the following
warnings in the system output

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:651)
	at org.opengda.detector.electronanalyser.client.views.RegionProgressComposite$CurrentPointListener.monitorChanged(RegionProgressComposite.java:424)
	at gov.aps.jca.event.LatestMonitorOnlyQueuedEventDispatcher$13.dispatch(LatestMonitorOnlyQueuedEventDispatcher.java:536)
	at gov.aps.jca.event.LatestMonitorOnlyQueuedEventDispatcher.run(LatestMonitorOnlyQueuedEventDispatcher.java:242)
	at java.base/java.lang.Thread.run(Thread.java:1583)

These errors were due to it getting the display when it had already been
disposed. I've fixed the if statements to check directly if it has been
disposed.

Change-Id: Ib81cc3c31973468d45768b7d49bc42eb2231cc59